### ISSUE TITLE
The applications shows a white page

### ISSUE THREAD

**Issue by danielgroen** [choss/java-xci-splitter#5]
Os: macOs 12.1
java version: 1.8.0_291
Xci splitter version: 1.4.0 (for mac ofc). 
_Also 1.4.1 does give me the same result_

What is going on?
![afbeelding](https://user-images.githubusercontent.com/6578052/162059418-98dcf453-291c-4b98-aaa0-91eb7cbacb18.png)

**Comment by gabrielcsapo** [comment]
you need to update releases/osx/pom.xml

before

```
<groupId>org.eclipse.platform</groupId>
<artifactId>org.eclipse.swt.cocoa.macosx.x86_64</artifactId>
<version>3.106.3</version>
```

after

```
<groupId>org.eclipse.platform</groupId>
<artifactId>org.eclipse.swt.cocoa.macosx.x86_64</artifactId>
<version>3.123.0</version>
```

and for me I needed to update

```
<entry>
	<key>JVM-Args</key>
	<value>-d64 -XstartOnFirstThread</value>
</entry>
```

to

```
<entry>
	<key>JVM-Args</key>
	<value> -XstartOnFirstThread</value>
</entry>
```

**Comment by gabrielcsapo** [comment]
This is the built version on my machine

[xci-splitter-osx-1.4.1-SNAPSHOT-capsule.jar.zip](https://github.com/choss/java-xci-splitter/files/11268678/xci-splitter-osx-1.4.1-SNAPSHOT-capsule.jar.zip)

**Comment by gabrielcsapo** [comment]
<img width="727" alt="Screenshot 2023-04-18 at 9 56 26 PM" src="https://user-images.githubusercontent.com/1854811/232970716-8445f389-612f-4b23-9a0e-3506227c9cbb.png">

**Comment by gabrielcsapo** [comment]
created a PR for this to get merged
